# Human-readable configuration for Login Server
mysql:
  host: localhost
  port: 3306
  database: rose
  user: rose
  password: rosepass
server:
  id: 1
  type: 0
  name: Loginserver
  ip: 0.0.0.0
  port: 29000
  lan_ip: 192.168.1.20
  lan_mask: 255.255.255.0
  login_pass: 123456
  char_pass: 123456
  world_pass: 123456
  min_access_level: 100
  use_threads: false
  create_login_account: false
  check_gameguard: true
