-- Core schema for ROSE Online servers (minimal set to boot)
-- Compatible with MySQL 5.7+/MariaDB 10.3+

CREATE TABLE IF NOT EXISTS accounts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  accesslevel SMALLINT NOT NULL DEFAULT 100,
  online BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS channels (
  id INT NOT NULL,
  type TINYINT NOT NULL, -- 0=login, 1=char, 2=world
  name VARCHAR(64) NOT NULL,
  host VARCHAR(64) NOT NULL,
  port INT NOT NULL,
  lanip VARCHAR(64) NOT NULL,
  lansubmask VARCHAR(32) NOT NULL,
  connected INT NOT NULL DEFAULT 0,
  maxconnections INT NOT NULL DEFAULT 100,
  owner INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id, type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ban_list (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ip VARCHAR(45) NOT NULL,
  startban BIGINT UNSIGNED NOT NULL DEFAULT 0, -- epoch seconds
  bantime BIGINT UNSIGNED NOT NULL DEFAULT 0   -- seconds
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- This table is queried on startup for presence check
CREATE TABLE IF NOT EXISTS list_npcs (
  id INT UNSIGNED PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Char server data used during startup
CREATE TABLE IF NOT EXISTS list_clan (
  id INT UNSIGNED PRIMARY KEY,
  logo INT NOT NULL DEFAULT 0,
  back INT NOT NULL DEFAULT 0,
  name VARCHAR(17) NOT NULL,
  cp INT NOT NULL DEFAULT 0,
  grade INT NOT NULL DEFAULT 0,
  slogan VARCHAR(30) NOT NULL DEFAULT '',
  news VARCHAR(260) NOT NULL DEFAULT '',
  rankingpoints INT NOT NULL DEFAULT 0,
  siglogo INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS characters (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userid INT UNSIGNED NOT NULL,
  char_name VARCHAR(17) NOT NULL,
  clanid INT NOT NULL DEFAULT 0,
  clan_rank INT NOT NULL DEFAULT 0,
  level INT NOT NULL DEFAULT 1,
  job INT NOT NULL DEFAULT 0,
  DeleteTime BIGINT UNSIGNED NOT NULL DEFAULT 0,
  INDEX (userid),
  INDEX (char_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS items_newchar (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  itemnum INT NOT NULL,
  itemtype INT NOT NULL,
  amount INT NOT NULL DEFAULT 1,
  slotnum INT NOT NULL DEFAULT 0,
  durability INT NOT NULL DEFAULT 40,
  sex TINYINT NOT NULL DEFAULT 0,
  premium TINYINT NOT NULL DEFAULT 0,
  active TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- World extras referenced by code (minimal columns)
CREATE TABLE IF NOT EXISTS map_exp (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  map_name VARCHAR(64) NOT NULL,
  map_id INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS warning_system (
  account_id INT UNSIGNED NOT NULL PRIMARY KEY,
  time_remaining INT NOT NULL DEFAULT 0,
  ban_type TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS LottoNumbers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  number1 INT NOT NULL,
  number2 INT NOT NULL,
  number3 INT NOT NULL,
  number4 INT NOT NULL,
  number5 INT NOT NULL,
  number6 INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS LottoEntries (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  char_name VARCHAR(20) NOT NULL,
  number1 INT NOT NULL,
  number2 INT NOT NULL,
  number3 INT NOT NULL,
  number4 INT NOT NULL,
  number5 INT NOT NULL,
  number6 INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS LottoWinners (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  char_name VARCHAR(20) NOT NULL,
  NumbersCorrect INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS LottoPrize (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Zulie BIGINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed minimal data used by code paths
INSERT IGNORE INTO list_npcs (id) VALUES (1);
